"""DTT Whitelist Validator package."""

from .version import VERSION, VERSION_DISPLAY, FULL_TITLE, BAT_FILE_NAME, ZIP_FILE_NAME, REPORT_PREFIX

__all__ = ["VERSION", "VERSION_DISPLAY", "FULL_TITLE", "BAT_FILE_NAME", "ZIP_FILE_NAME", "REPORT_PREFIX"]
